config/routes.rb
SampleCPO::Application.routes.draw do

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :following, :followers # the URIs will look like /users/1/following and /users/1/followers
      match '/confirm/:confirmation_code', via: :get, to: 'users#confirm', as: :confirm 
    end
  end

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :products do
    collection do
      post :import
    end
  end

  resources :orders
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :item_number, :description, :category, :current_retail_price, :current_cpo, :current_point_value

  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item

	VALID_ITEM_NUMBER_REGEX = /\A\d{2,4}[-12RCWPHTSDBK]{0,6}\z/
  validates :item_number, presence: true, format: { with: VALID_ITEM_NUMBER_REGEX }, uniqueness: true
  validates :description, presence: true
  validates :category, presence: true
  validates :current_retail_price, presence: true, numericality: true
  #validates :current_cpo, numericality: true
  #validates :current_point_value, numericality: true
  

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
	  spreadsheet = open_spreadsheet(file)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	    row = Hash[[header, spreadsheet.row(i)].transpose]
	    product = find_by_id(row["id"]) || new
	    product.attributes = row.to_hash.slice(*accessible_attributes)
	    product.save!
	  end
	end

	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when '.csv' then Roo::Csv.new(file.path, nil, :ignore)
	  #when '.ods' then Openoffice.new(file.path, nil, :ignore)
	  when '.xls' then Roo::Excel.new(file.path, nil, :ignore)
	  when '.xlsx' then Excelx.new(file.path, nil, :ignore)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end

	private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_filter :signed_in_user,  only: [:show, :new, :create, :edit, :update, :destroy, :index, :import]
	before_filter :admin_user,      only: [:new, :create, :edit, :update, :destroy, :import]

	respond_to :html, :json

	def show
		@product = Product.find(params[:id])
	end

	def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(params[:product])
    if @product.save
      flash[:success] = "Product #{@product.item_number} added"
      redirect_to products_url
    else
      render 'new'
    end
  end

  def edit
  	@product = Product.find(params[:id])
  end

=begin
  def update
  	@product = Product.find(params[:id])
  	if @product.update_attributes(params[:product])
      flash[:success] = "Product updated"
      redirect_to products_url
    else
      render 'edit'
    end
  end



	def update
	  @product = Product.find(params[:id])

	  respond_to do |format|
	    if @product.update_attributes(params[:product])
	      format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
	      format.json { respond_with_bip(@product) }
	    else
	      format.html { render :action => "edit" }
	      format.json { respond_with_bip(@product) }
	    end
	  end
	end



	def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
    	flash[:success] = "Successfully updated #{@product.item}"
    end
    # respond_with(@product, :location => products_url)
  end
=end

	def update
    @product = Product.find(params[:id])
    @product.update_attributes(params[:product])
    respond_with @product
  end

  def destroy
  	@product = Product.find(params[:id])
    #if current_user.admin? 
    	proditnum = "#{@product.item_number}"
      @product.destroy 
      flash[:success] = "Product #{proditnum} removed."
      redirect_to products_url
    #else
    #	 flash[:error] = "You do not have permission to remove Product #{proditnum}"
    #  redirect_to products_url
    #end
  end

  def index
	  @products = Product.order(:item_number)
	  respond_to do |format|
	    format.html
	    format.csv { send_data @products.to_csv }
	    format.xls #{ send_data @products.to_csv(col_sep: "\t") }
	  end
	end

	def import
	  Product.import(params[:file])
	  flash[:success] = "Products imported."
	  redirect_to products_url
	end

	private

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :item_number %>
<%= f.text_field :item_number %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :category %>
<%= f.text_field :category %>

<%= f.label :current_retail_price %>
<%= f.text_field :current_retail_price %>

<%= f.label :current_cpo %>
<%= f.text_field :current_cpo %>

<%= f.label :current_point_value %>
<%= f.text_field :current_point_value %>

app/views/products/_product.html.erb
<% product ||= @product %>
<tr>
	<% if current_user.admin? %>
		<td>
			<% unless controller.action_name == 'show' %>
				<%= link_to 'show', product %> |
			<% end %>
			<%= link_to 'edit', edit_product_path(product) %> | 
	  	<%= link_to "destroy", product, method: :delete, data: { confirm: "You sure?" } %>
  	</td>
  	<td><%= best_in_place product, :item_number %></td>
	<% else %>
		<td>
			<% unless controller.action_name == 'show' %>
		    <%= link_to product.item_number, product %>
			<% else %>
				<%= product.item_number %>
			<% end %>
		</td>
	<% end %>
  <td><%= best_in_place_if current_user.admin?, product, :description %></td>
  <td><%= best_in_place_if current_user.admin?, product, :category %></td>
  <td><%= best_in_place_if current_user.admin?, product, :current_retail_price, display_with: :number_to_currency %></td>
  <td><%= best_in_place_if current_user.admin?, product, :current_cpo %></td>
  <td><%= best_in_place_if current_user.admin?, product, :current_point_value %></td>
</tr>

app/views/products/edit.html.erb
<% provide(:title, "Edit Product") %> 
<h1>Edit <%= "#{@product.item_number}" %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@product) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'back to All Products', products_path %>

app/views/products/index.html.erb
<% provide(:title, "All Products") %> 
<h1>All Products</h1>

<% if current_user.admin? %>
  <p>
    <%= link_to 'add new Product', new_product_path %>
  </p>
  <div>
    <%= form_tag import_products_path, multipart: true do %>
      <%= file_field_tag :file %>
      <button type="submit" class="btn btn-primary">
        <%= submit_tag "Import Products" %>
      </button>
    <% end %>
  </div>
  <p>
    download list as:
    <%= link_to ".csv", products_path(format: "csv") %> |
    <%= link_to ".xls", products_path(format: "xls") %>
  </p>
<% end %>

<table id="products" class="table table-striped table-bordered">
  <tr>
    <% if current_user.admin? %>
      <th>(admin)</th>
    <% end %>
    <th>Item Number</th>
    <th>Description</th>
    <th>Category</th>
    <th>Retail Price</th>
    <th>CPO</th>
    <th>Point Value</th>
  </tr>
  <% @products.each do |product| %>
    <%= render 'product', product: product %>
  <% end %>
</table>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Item Number</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Category</Data></Cell>
        <Cell><Data ss:Type="String">Retail Price</Data></Cell>
        <Cell><Data ss:Type="String">CPO</Data></Cell>
        <Cell><Data ss:Type="String">Point Value</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="String"><%= product.item_number %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.category %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.current_retail_price %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.current_cpo %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.current_point_value %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/new.html.erb
<% provide(:title, 'Add Product') %>
<h1>Add Product</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@product) do |f| %>
    	<%= render 'fields', f: f %>
      <%= f.submit "Create product", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

<%= link_to 'back to All Products', products_path %>

app/views/products/show.html.erb
<% provide(:title, 'View Product') %>
<h1><%= "#{@product.item_number}" %></h1>

<table id="products" class="table table-striped table-bordered">
  <tr>
    <% if current_user.admin? %>
      <th>(admin)</th>
    <% end %>
    <th>Item Number</th>
    <th>Description</th>
    <th>Category</th>
    <th>Retail Price</th>
    <th>CPO</th>
    <th>Point Value</th>
  </tr>
  <%= render @product %>
</table>

<%= link_to 'back to All Products', products_path %>